//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate : HR2.EF.DAL.IEFEntity
    {
        public int CandidateId { get; set; }
        public Nullable<int> VacancyId { get; set; }
        public string CandidateStatus { get; set; }
        public string CandidateName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string MobileNumber { get; set; }
        public string eMail { get; set; }
        public string Keywords { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateOfApplication { get; set; }
        public string MaritialStatus { get; set; }
    }
}
