//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category : HR2.EF.DAL.IEFEntity
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategorySName { get; set; }
        public string OTFormula { get; set; }
        public int MinOT { get; set; }
        public int IsMaxOT { get; set; }
        public int MaxOT { get; set; }
        public int IsConsiderFirstAndLastPunch { get; set; }
        public int GraceTimeForLateComing { get; set; }
        public int GracetimeForEarlyGoing { get; set; }
        public int IsNeglectLastInPunch { get; set; }
        public int IsWeeklyOff1 { get; set; }
        public string WeeklyOff1Day { get; set; }
        public int IsWeeklyOff2 { get; set; }
        public string WeeklyOff2Day { get; set; }
        public string WeeklyOff2days { get; set; }
        public Nullable<int> IsConsiderEarlyComingPunch { get; set; }
        public Nullable<int> IsConsiderLateGoingPunch { get; set; }
        public int IsDeductBreakHourFromD { get; set; }
        public int IsCHalfForLessD { get; set; }
        public int CHalfForLessDMins { get; set; }
        public int IsCAbsentDisLessThan { get; set; }
        public int CAbsentDisLessThanMins { get; set; }
        public int IsCHalfForLessD_P { get; set; }
        public int CHalfForLessDMins_P { get; set; }
        public int IsCAbsentDisLessThan_P { get; set; }
        public int CAbsentDisLessThanMins_P { get; set; }
        public int IsPrefixMarkWOAndHAbsent { get; set; }
        public int IsSuffixMarkWOAndHAbsent { get; set; }
        public int IsBothMarkWOAndHAbsent { get; set; }
        public int IsMark { get; set; }
        public string AbsentType { get; set; }
        public int LateDay { get; set; }
        public int IsMarkHalfDay_LateBy { get; set; }
        public int MarkHalfDay_LateByMins { get; set; }
        public int IsMarkHalfDay_EarlyGoing { get; set; }
        public int MarkHalfDay_EarlyGoing { get; set; }
        public int RecordStatus { get; set; }
        public string ForSinglePunch { get; set; }
        public Nullable<int> ConsiderWP_HPInOT { get; set; }
        public Nullable<int> IsCalculateHalfCompOff { get; set; }
        public Nullable<int> IsCalculateNoCompOff { get; set; }
        public Nullable<int> CalculateHalfCompOffMins { get; set; }
        public Nullable<int> CalculateNoCompOffMins { get; set; }
        public Nullable<int> IsContiLateByWithEarlyBy { get; set; }
        public Nullable<int> IsDeductBreakDuInOTWOHP { get; set; }
        public Nullable<int> FlexiShiftId { get; set; }
        public Nullable<int> IsAdjustLateComWithEarly { get; set; }
        public Nullable<int> AdjustLateComWithEarlyDays { get; set; }
        public Nullable<int> IsDeductCon_Le_Ab_LateByDays { get; set; }
        public Nullable<int> IsDeduct_Le_Ab_LateByMins { get; set; }
        public Nullable<int> IsDeduct_Le_Ab_EarlByMins { get; set; }
        public Nullable<int> IsPerformSameConsecutiveLate { get; set; }
        public Nullable<int> IsDeductContiLateLeave { get; set; }
        public Nullable<int> IsDeductLateByLeave { get; set; }
        public Nullable<int> IsDeductEarlyByLeave { get; set; }
        public string DeductContiLateLeaveDay { get; set; }
        public Nullable<int> DeductContiLateLeaveType1 { get; set; }
        public Nullable<int> DeductContiLateLeaveType2 { get; set; }
        public Nullable<int> DeductContiLateLeaveType3 { get; set; }
        public Nullable<int> DeductContiLateLeaveLateFor { get; set; }
        public string LateEarlyRecurringType { get; set; }
        public string DeductLateByLeaveDay { get; set; }
        public Nullable<int> DeductLateByLeaveType1 { get; set; }
        public Nullable<int> DeductLateByLeaveType2 { get; set; }
        public Nullable<int> DeductLateByLeaveType3 { get; set; }
        public Nullable<int> DeductLateByLeaveLateFor { get; set; }
        public string DeductEarlyByLeaveDay { get; set; }
        public Nullable<int> DeductEarlyByLeaveType1 { get; set; }
        public Nullable<int> DeductEarlyByLeaveType2 { get; set; }
        public Nullable<int> DeductEarlyByLeaveType3 { get; set; }
        public Nullable<int> DeductEarlyByLeaveEarlyFor { get; set; }
        public Nullable<int> IsDeductCon_Le_Ab_EarlyByDays { get; set; }
        public Nullable<int> IsMarkConEarly { get; set; }
        public string AbsentTypeConEarly { get; set; }
        public Nullable<int> ConEarlyDay { get; set; }
        public Nullable<int> IsDeductContiEarlyLeave { get; set; }
        public string DeductContiEarlyLeaveDay { get; set; }
        public Nullable<int> DeductContiEarlyLeaveType1 { get; set; }
        public Nullable<int> DeductContiEarlyLeaveType2 { get; set; }
        public Nullable<int> DeductContiEarlyLeaveType3 { get; set; }
        public Nullable<int> DeductContiEarlyLeaveEarlyFor { get; set; }
        public Nullable<int> IsPerformSameConsecutiveEarly { get; set; }
    }
}
