//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company : HR2.EF.DAL.IEFEntity
    {
        public int CompanyId { get; set; }
        public string CompanyFName { get; set; }
        public string CompanySName { get; set; }
        public string CompanyAddress { get; set; }
        public Nullable<int> CompanyIsVisible { get; set; }
        public string CompanyeMail { get; set; }
        public string CompanyWebsite { get; set; }
        public int RecordStatus { get; set; }
    }
}
