//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentShift : HR2.EF.DAL.IEFEntity
    {
        public int DepartmentShiftId { get; set; }
        public int DepartmentId { get; set; }
        public System.DateTime ShiftDate { get; set; }
        public int ShiftId { get; set; }
        public string ShiftType { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    }
}
