//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation : HR2.EF.DAL.IEFEntity
    {
        public int DesignationId { get; set; }
        public string DesignationsName { get; set; }
        public string DesignationCode { get; set; }
        public Nullable<int> NormalNoticePeriodRequired { get; set; }
        public Nullable<int> ProbationNoticePeriodRequired { get; set; }
    }
}
