//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device : HR2.EF.DAL.IEFEntity
    {
        public int DeviceId { get; set; }
        public string DeviceFName { get; set; }
        public string DeviceSName { get; set; }
        public string DeviceDirection { get; set; }
        public string SerialNumber { get; set; }
        public string ConnectionType { get; set; }
        public string IpAddress { get; set; }
        public string BaudRate { get; set; }
        public string ComPort { get; set; }
        public System.DateTime LastLogDownloadDate { get; set; }
        public string CommKey { get; set; }
        public string TransactionStamp { get; set; }
        public Nullable<System.DateTime> LastPing { get; set; }
        public string DeviceType { get; set; }
        public string OpStamp { get; set; }
        public Nullable<int> DownLoadType { get; set; }
        public string Timezone { get; set; }
        public string DeviceLocation { get; set; }
        public string TimeOut { get; set; }
        public Nullable<int> IsRealTime { get; set; }
        public string TransTimes { get; set; }
        public string TransInterval { get; set; }
        public string DeviceVendor { get; set; }
        public string DeviceInfo { get; set; }
        public string TransFlag { get; set; }
        public Nullable<int> MasterDeviceId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DownloadedLogCount { get; set; }
    }
}
