//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceCommand : HR2.EF.DAL.IEFEntity
    {
        public int DeviceCommandId { get; set; }
        public string Title { get; set; }
        public string DeviceCommand1 { get; set; }
        public string SerialNumber { get; set; }
        public string Status { get; set; }
        public string CreationDate { get; set; }
        public string ExecutionDate { get; set; }
        public string ReturnValue { get; set; }
    }
}
