//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesAudit : HR2.EF.DAL.IEFEntity
    {
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeCode { get; set; }
        public string StringCode { get; set; }
        public Nullable<int> NumericCode { get; set; }
        public string Gender { get; set; }
        public int CompanyId { get; set; }
        public int DepartmentId { get; set; }
        public string Designation { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> DOR { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public string EmployeeCodeInDevice { get; set; }
        public string EmployeeRFIDNumber { get; set; }
        public string EmployementType { get; set; }
        public string Status { get; set; }
        public string EmployeeDevicePassword { get; set; }
        public string EmployeeDeviceGroup { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string ResidentialAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Nomenee1 { get; set; }
        public string Nomenee2 { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> RecordStatus { get; set; }
        public string C1 { get; set; }
        public string C2 { get; set; }
        public string C3 { get; set; }
        public string C4 { get; set; }
        public string C5 { get; set; }
        public string C6 { get; set; }
        public string C7 { get; set; }
        public string Location { get; set; }
        public string BLOODGROUP { get; set; }
        public string WorkPlace { get; set; }
        public string ExtensionNo { get; set; }
        public string LoginName { get; set; }
        public string LoginPassword { get; set; }
        public string Grade { get; set; }
        public string Team { get; set; }
        public Nullable<int> IsRecieveNotification { get; set; }
        public Nullable<int> HolidayGroup { get; set; }
        public Nullable<int> ShiftGroupId { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<int> ShiftRotationMasterId { get; set; }
        public string ReportTo { get; set; }
        public string ShiftType { get; set; }
        public string OfficialPhone { get; set; }
        public string OfficialMobile { get; set; }
        public string PersonaleMailID { get; set; }
        public string UIDNo { get; set; }
        public string PANNo { get; set; }
        public string VoterIdNo { get; set; }
        public Nullable<int> MultiShiftGroupId { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public string AndroidDeviceIMEINo { get; set; }
        public Nullable<int> IsMarkAndroidWebAttendance { get; set; }
        public string PushNotificationId { get; set; }
        public Nullable<int> IsSendApproveDeclineSMS { get; set; }
        public Nullable<int> IsSendPushNotification { get; set; }
        public string BankAccountNumber { get; set; }
        public string ModeOfPayment { get; set; }
        public string ESINo { get; set; }
        public string ESIDispensary { get; set; }
        public string PFNo { get; set; }
        public Nullable<int> SalaryStructureId { get; set; }
    }
}
