//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaveCreditHistory : HR2.EF.DAL.IEFEntity
    {
        public int EmployeeLeaveCreditHistoryId { get; set; }
        public int EmployeeId { get; set; }
        public int LeaveTypeId { get; set; }
        public System.DateTime CreditedDate { get; set; }
        public System.DateTime CreditedCycle { get; set; }
        public double Credited { get; set; }
    }
}
