//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDocument : HR2.EF.DAL.IEFEntity
    {
        public int EmployeeDocumentId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string DocumentTitle { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public string Extension { get; set; }
    }
}
