//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaveEntry : HR2.EF.DAL.IEFEntity
    {
        public int EmployeeLeaveEntryId { get; set; }
        public int LeaveTypeId { get; set; }
        public string LeaveStatus { get; set; }
        public int LeaveDuration { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime LeaveDate { get; set; }
        public int IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public string Remarks { get; set; }
        public string LastModifiedBy { get; set; }
        public string Reason { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string ApplicableSession { get; set; }
        public string LeaveApplicationStatus { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDeclinedDate { get; set; }
        public string ManagerRemarks { get; set; }
        public Nullable<int> IsAutoDeduct { get; set; }
    }
}
