//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesLeavesBalance : HR2.EF.DAL.IEFEntity
    {
        public int EmployeeLeaveBalanceId { get; set; }
        public int EmployeeId { get; set; }
        public int LeaveTypeId { get; set; }
        public Nullable<double> LeaveBalance { get; set; }
        public Nullable<int> LeaveYear { get; set; }
        public Nullable<int> LeaveLapse { get; set; }
        public Nullable<int> IsLeaveCarryForwarded { get; set; }
    }
}
