//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCompOffRequest : HR2.EF.DAL.IEFEntity
    {
        public int EmployeeCompOffRequestId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> WOP_HPDate { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
