//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveTypeHistory : HR2.EF.DAL.IEFEntity
    {
        public int LeaveTypeHistoryId { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public string LeaveTypeDetails { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
