//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType : HR2.EF.DAL.IEFEntity
    {
        public int LeaveTypeId { get; set; }
        public string LeaveTypeName { get; set; }
        public string LeaveTypeCode { get; set; }
        public Nullable<double> CarryForwardLimit { get; set; }
        public string Gender { get; set; }
        public Nullable<double> YearlyLimit { get; set; }
        public string Description { get; set; }
        public Nullable<int> IsAllowNegativeBalance { get; set; }
        public Nullable<int> RecordStatus { get; set; }
        public string AllotOnMonthDay { get; set; }
        public string AllotmentType { get; set; }
        public Nullable<int> IsLeaveEncashment { get; set; }
        public Nullable<double> LeaveEncashmentMinBalance { get; set; }
        public Nullable<int> IsLossOfPay { get; set; }
        public string AllotFrom { get; set; }
        public Nullable<int> AllotAfterDaysEmployment { get; set; }
        public Nullable<double> IncreaseLeaveBy { get; set; }
        public Nullable<int> EmploymentCompleted { get; set; }
        public string AvailFrom { get; set; }
        public Nullable<int> AvailAfterDaysEmployment { get; set; }
        public Nullable<System.DateTime> LastLeaveCreditedOn { get; set; }
        public string LeaveTypeEffFrom { get; set; }
        public Nullable<int> GraceDaysForConfirmation { get; set; }
        public Nullable<int> GraceDaysEmploymentCompleted { get; set; }
    }
}
