//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailDetail : HR2.EF.DAL.IEFEntity
    {
        public int MaildetailsId { get; set; }
        public string email { get; set; }
        public string SMTPHost { get; set; }
        public string Port { get; set; }
        public Nullable<int> EnableSSL { get; set; }
        public string SMTPUserName { get; set; }
        public string SMTPPassword { get; set; }
    }
}
