//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterSetting : HR2.EF.DAL.IEFEntity
    {
        public int MasterDetailsId { get; set; }
        public int IsAlphaNumericEmployeeCode { get; set; }
        public int IsFixedShift { get; set; }
        public string ShiftBeginTime { get; set; }
        public string ShiftEndTime { get; set; }
        public int IsDeviceCodeSame { get; set; }
        public string AttendanceYearStartOn { get; set; }
        public string LiecenceKey { get; set; }
        public Nullable<int> PunchBeginDuration { get; set; }
        public string Version { get; set; }
        public Nullable<int> MinDiffBetweenTwoPunch { get; set; }
        public Nullable<int> IsAutoShift { get; set; }
        public string MemoLateEarlySubject { get; set; }
        public string MemoMissedPunchSubject { get; set; }
        public string MemoSignature { get; set; }
        public string MemoAbsentText { get; set; }
        public string MemoLateEarlyText { get; set; }
        public string MemoMissedPunchText { get; set; }
        public string MemoAbsentSubject { get; set; }
        public string MemoHalfDayForLateEarlySubject { get; set; }
        public string MemoHalfDayForLateEarlyText { get; set; }
        public string TrialDate { get; set; }
        public Nullable<int> IsAutoBackUp { get; set; }
        public string AutoBackuppath { get; set; }
        public Nullable<int> BackupDays { get; set; }
        public Nullable<System.DateTime> LastBackupDate { get; set; }
        public Nullable<int> RestrictedHolidayLimit { get; set; }
        public Nullable<int> Duration_LateBy_EarlyByInMins { get; set; }
        public string EmployeePhotoRepository { get; set; }
        public string EmployeeDocumentRepository { get; set; }
        public Nullable<int> IsUsePushDataCollectorService { get; set; }
        public Nullable<int> ODAppliedBeforeDays { get; set; }
        public Nullable<int> IsBiometricAttendance { get; set; }
        public string WEBURL { get; set; }
        public Nullable<int> IsLockAttendance { get; set; }
        public Nullable<int> AttendanceLockOn { get; set; }
        public Nullable<int> QuarterDayLeaveDuration { get; set; }
        public string DEFAULTGROUPBYREPORTS { get; set; }
        public Nullable<int> IsBackgroundLeaveRunning { get; set; }
        public string OptionalHolidayType { get; set; }
        public string CloudURL { get; set; }
        public string CloudCompanyName { get; set; }
        public string CalcAutoShiftAsPer { get; set; }
        public Nullable<int> IsSendRealTimeMail { get; set; }
        public Nullable<int> IsShowDailyCustomReport1 { get; set; }
        public Nullable<int> IsShowDailyCustomReport2 { get; set; }
        public Nullable<int> IsShowDailyCustomReport3 { get; set; }
        public Nullable<int> IsShowMonthlyCustomReport1 { get; set; }
        public Nullable<int> IsShowMonthlyCustomReport2 { get; set; }
        public Nullable<int> IsShowMonthlyCustomReport3 { get; set; }
        public string DailyCustomizeReport1Name { get; set; }
        public string DailyCustomizeReport2Name { get; set; }
        public string DailyCustomizeReport3Name { get; set; }
        public string MonthlyCustomizeReport1Name { get; set; }
        public string MonthlyCustomizeReport2Name { get; set; }
        public string MonthlyCustomizeReport3Name { get; set; }
        public Nullable<int> SMSprovision { get; set; }
        public Nullable<int> RestrictedHolidayprovision { get; set; }
        public Nullable<int> CompOffprovision { get; set; }
        public Nullable<int> MultiShift { get; set; }
        public Nullable<int> ShiftRoster { get; set; }
        public string AppPhysicalPath { get; set; }
    }
}
