//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageLog : HR2.EF.DAL.IEFEntity
    {
        public int MessageLogId { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public string EmployeeCode { get; set; }
        public string MessageText { get; set; }
        public string Status { get; set; }
        public Nullable<int> IsSuccess { get; set; }
        public string LogDate { get; set; }
        public string SMSLogMobileNumber { get; set; }
    }
}
