//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiShift : HR2.EF.DAL.IEFEntity
    {
        public int MultiShiftId { get; set; }
        public string MultiShiftName { get; set; }
        public string MultiShiftCode { get; set; }
        public string MultiShiftBeginTime { get; set; }
        public string MultiShiftEndTime { get; set; }
        public Nullable<int> MultiShiftDuration { get; set; }
        public Nullable<int> RecordStatus { get; set; }
        public Nullable<int> PunchBeginDuration { get; set; }
        public Nullable<int> PunchEndDuration { get; set; }
        public Nullable<int> IsGraceTimeApplicable { get; set; }
        public string GraceTime { get; set; }
        public Nullable<int> IsPunchBeginDuration { get; set; }
        public Nullable<int> IsPunchEndDuration { get; set; }
        public Nullable<int> MultiShiftGroupId { get; set; }
    }
}
