//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiShiftAttendanceLog : HR2.EF.DAL.IEFEntity
    {
        public int MultiShiftAttendanceLogsId { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> MultiShiftId1 { get; set; }
        public string MultiShiftId1InTime { get; set; }
        public Nullable<int> MultiShiftId1InDeviceId { get; set; }
        public string MultiShiftId1OutTime { get; set; }
        public Nullable<int> MultiShiftId1OutDeviceId { get; set; }
        public string MultiShiftId1Duration { get; set; }
        public string MultiShiftId1LateBy { get; set; }
        public string MultiShiftId1EarlyBy { get; set; }
        public Nullable<int> MultiShiftId2 { get; set; }
        public string MultiShiftId2InTime { get; set; }
        public Nullable<int> MultiShiftId2InDeviceId { get; set; }
        public string MultiShiftId2OutTime { get; set; }
        public Nullable<int> MultiShiftId2OutDeviceId { get; set; }
        public string MultiShiftId2Duration { get; set; }
        public string MultiShiftId2LateBy { get; set; }
        public string MultiShiftId2EarlyBy { get; set; }
        public Nullable<int> MultiShiftId3 { get; set; }
        public string MultiShiftId3InTime { get; set; }
        public Nullable<int> MultiShiftId3InDeviceId { get; set; }
        public string MultiShiftId3OutTime { get; set; }
        public Nullable<int> MultiShiftId3OutDeviceId { get; set; }
        public string MultiShiftId3Duration { get; set; }
        public string MultiShiftId3LateBy { get; set; }
        public string MultiShiftId3EarlyBy { get; set; }
        public Nullable<int> MultiShiftId4 { get; set; }
        public string MultiShiftId4InTime { get; set; }
        public Nullable<int> MultiShiftId4InDeviceId { get; set; }
        public string MultiShiftId4OutTime { get; set; }
        public Nullable<int> MultiShiftId4OutDeviceId { get; set; }
        public string MultiShiftId4Duration { get; set; }
        public string MultiShiftId4LateBy { get; set; }
        public string MultiShiftId4EarlyBy { get; set; }
        public Nullable<int> MultiShiftId5 { get; set; }
        public string MultiShiftId5InTime { get; set; }
        public Nullable<int> MultiShiftId5InDeviceId { get; set; }
        public string MultiShiftId5OutTime { get; set; }
        public Nullable<int> MultiShiftId5OutDeviceId { get; set; }
        public string MultiShiftId5Duration { get; set; }
        public string MultiShiftId5LateBy { get; set; }
        public string MultiShiftId5EarlyBy { get; set; }
        public Nullable<int> MultiShiftId6 { get; set; }
        public string MultiShiftId6InTime { get; set; }
        public Nullable<int> MultiShiftId6InDeviceId { get; set; }
        public string MultiShiftId6OutTime { get; set; }
        public Nullable<int> MultiShiftId6OutDeviceId { get; set; }
        public string MultiShiftId6Duration { get; set; }
        public string MultiShiftId6LateBy { get; set; }
        public string MultiShiftId6EarlyBy { get; set; }
        public Nullable<int> MultiShiftId7 { get; set; }
        public string MultiShiftId7InTime { get; set; }
        public Nullable<int> MultiShiftId7InDeviceId { get; set; }
        public string MultiShiftId7OutTime { get; set; }
        public Nullable<int> MultiShiftId7OutDeviceId { get; set; }
        public string MultiShiftId7Duration { get; set; }
        public string MultiShiftId7LateBy { get; set; }
        public string MultiShiftId7EarlyBy { get; set; }
        public Nullable<int> MultiShiftId8 { get; set; }
        public string MultiShiftId8InTime { get; set; }
        public Nullable<int> MultiShiftId8InDeviceId { get; set; }
        public string MultiShiftId8OutTime { get; set; }
        public Nullable<int> MultiShiftId8OutDeviceId { get; set; }
        public string MultiShiftId8Duration { get; set; }
        public string MultiShiftId8LateBy { get; set; }
        public string MultiShiftId8EarlyBy { get; set; }
        public Nullable<int> MultiShiftId9 { get; set; }
        public string MultiShiftId9InTime { get; set; }
        public Nullable<int> MultiShiftId9InDeviceId { get; set; }
        public string MultiShiftId9OutTime { get; set; }
        public Nullable<int> MultiShiftId9OutDeviceId { get; set; }
        public string MultiShiftId9Duration { get; set; }
        public string MultiShiftId9LateBy { get; set; }
        public string MultiShiftId9EarlyBy { get; set; }
        public string IsOnLeave { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public string LeaveType { get; set; }
        public string LeaveDuration { get; set; }
        public string LeaveStatus { get; set; }
        public string LeaveRemarks { get; set; }
        public string IsonSpecialOff { get; set; }
        public string SpecialOffType { get; set; }
        public string SpecialOffRemark { get; set; }
        public string SpecialOffDuration { get; set; }
        public string WeeklyOff { get; set; }
        public string Holiday { get; set; }
        public string PunchRecords { get; set; }
        public string PunchDirections { get; set; }
        public string PunchDevicesName { get; set; }
        public string Present { get; set; }
        public string Absent { get; set; }
        public string OverTime { get; set; }
        public string OverTimeE { get; set; }
        public string MissedOutPunch { get; set; }
        public string MissedInPunch { get; set; }
        public string Remarks { get; set; }
        public string IsOnRestrictedHoliday { get; set; }
        public string IsOnCompOff { get; set; }
        public string ReportPunchRecords { get; set; }
        public string MultiShift1PunchRecords { get; set; }
        public string MultiShift2PunchRecords { get; set; }
        public string MultiShift3PunchRecords { get; set; }
        public string MultiShift4PunchRecords { get; set; }
        public string MultiShift5PunchRecords { get; set; }
        public string MultiShift6PunchRecords { get; set; }
        public string MultiShift7PunchRecords { get; set; }
        public string MultiShift8PunchRecords { get; set; }
        public string MultiShift9PunchRecords { get; set; }
        public string MultiShift1Remarks { get; set; }
        public string MultiShift1StatusCode { get; set; }
        public string MultiShift1DetailedStatusCode { get; set; }
        public string MultiShift1Status { get; set; }
        public string MultiShift1DetailedStatus { get; set; }
        public string MultiShift2Remarks { get; set; }
        public string MultiShift2StatusCode { get; set; }
        public string MultiShift2DetailedStatusCode { get; set; }
        public string MultiShift2Status { get; set; }
        public string MultiShift2DetailedStatus { get; set; }
        public string MultiShift3Remarks { get; set; }
        public string MultiShift3StatusCode { get; set; }
        public string MultiShift3DetailedStatusCode { get; set; }
        public string MultiShift3Status { get; set; }
        public string MultiShift3DetailedStatus { get; set; }
        public string MultiShift4Remarks { get; set; }
        public string MultiShift4StatusCode { get; set; }
        public string MultiShift4DetailedStatusCode { get; set; }
        public string MultiShift4Status { get; set; }
        public string MultiShift4DetailedStatus { get; set; }
        public string MultiShift5Remarks { get; set; }
        public string MultiShift5StatusCode { get; set; }
        public string MultiShift5DetailedStatusCode { get; set; }
        public string MultiShift5Status { get; set; }
        public string MultiShift5DetailedStatus { get; set; }
        public string MultiShift6Remarks { get; set; }
        public string MultiShift6StatusCode { get; set; }
        public string MultiShift6DetailedStatusCode { get; set; }
        public string MultiShift6Status { get; set; }
        public string MultiShift6DetailedStatus { get; set; }
        public string MultiShift7Remarks { get; set; }
        public string MultiShift7StatusCode { get; set; }
        public string MultiShift7DetailedStatusCode { get; set; }
        public string MultiShift7Status { get; set; }
        public string MultiShift7DetailedStatus { get; set; }
        public string MultiShift8Remarks { get; set; }
        public string MultiShift8StatusCode { get; set; }
        public string MultiShift8DetailedStatusCode { get; set; }
        public string MultiShift8Status { get; set; }
        public string MultiShift8DetailedStatus { get; set; }
        public string MultiShift9Remarks { get; set; }
        public string MultiShift9StatusCode { get; set; }
        public string MultiShift9DetailedStatusCode { get; set; }
        public string MultiShift9Status { get; set; }
        public string MultiShift9DetailedStatus { get; set; }
    }
}
