//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiShiftEmployeeShift : HR2.EF.DAL.IEFEntity
    {
        public int MultiShiftEmployeeShiftId { get; set; }
        public Nullable<int> MultiShiftId1 { get; set; }
        public Nullable<int> MultiShiftId2 { get; set; }
        public Nullable<int> MultiShiftId3 { get; set; }
        public Nullable<int> MultiShiftId4 { get; set; }
        public Nullable<int> MultiShiftId5 { get; set; }
        public Nullable<int> MultiShiftId6 { get; set; }
        public Nullable<int> MultiShiftId7 { get; set; }
        public Nullable<int> MultiShiftId8 { get; set; }
        public Nullable<int> MultiShiftId9 { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> Shiftdate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    }
}
