//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftRoster : HR2.EF.DAL.IEFEntity
    {
        public int ShiftRotationMasterId { get; set; }
        public string ShiftRotationMasterName { get; set; }
        public Nullable<System.DateTime> BeginDay { get; set; }
        public Nullable<System.DateTime> EndDay { get; set; }
        public string SHIFTROTATIONTYPE { get; set; }
        public Nullable<int> MondayShiftId { get; set; }
        public Nullable<int> TuesdayShiftId { get; set; }
        public Nullable<int> WednesdayShiftId { get; set; }
        public Nullable<int> ThursdayShiftId { get; set; }
        public Nullable<int> FridayShiftId { get; set; }
        public Nullable<int> SaturdayShiftId { get; set; }
        public Nullable<int> SundayShiftId { get; set; }
        public Nullable<int> ShiftId1 { get; set; }
        public Nullable<int> ShiftId2 { get; set; }
        public Nullable<int> ShiftId3 { get; set; }
        public Nullable<int> ShiftId4 { get; set; }
        public Nullable<int> ShiftId5 { get; set; }
        public Nullable<int> ShiftId6 { get; set; }
        public Nullable<int> ShiftId7 { get; set; }
        public Nullable<int> ShiftId8 { get; set; }
        public Nullable<int> ShiftId9 { get; set; }
        public Nullable<int> ShiftId10 { get; set; }
        public Nullable<int> ShiftId20 { get; set; }
        public Nullable<int> ShiftId19 { get; set; }
        public Nullable<int> ShiftId18 { get; set; }
        public Nullable<int> ShiftId17 { get; set; }
        public Nullable<int> ShiftId16 { get; set; }
        public Nullable<int> ShiftId15 { get; set; }
        public Nullable<int> ShiftId14 { get; set; }
        public Nullable<int> ShiftId13 { get; set; }
        public Nullable<int> ShiftId12 { get; set; }
        public Nullable<int> ShiftId11 { get; set; }
        public Nullable<int> ShiftId30 { get; set; }
        public Nullable<int> ShiftId29 { get; set; }
        public Nullable<int> ShiftId28 { get; set; }
        public Nullable<int> ShiftId27 { get; set; }
        public Nullable<int> ShiftId26 { get; set; }
        public Nullable<int> ShiftId25 { get; set; }
        public Nullable<int> ShiftId24 { get; set; }
        public Nullable<int> ShiftId23 { get; set; }
        public Nullable<int> ShiftId22 { get; set; }
        public Nullable<int> ShiftId21 { get; set; }
        public Nullable<int> ShiftId31 { get; set; }
        public Nullable<int> WeeklyOff1 { get; set; }
        public Nullable<int> WeeklyOff2 { get; set; }
        public string WeeklyOff1Day { get; set; }
        public string WeeklyOff2Day { get; set; }
        public string WeeklyOff2Occurrence { get; set; }
    }
}
