//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift : HR2.EF.DAL.IEFEntity
    {
        public int ShiftId { get; set; }
        public string ShiftName { get; set; }
        public string ShiftCode { get; set; }
        public string BeginTime { get; set; }
        public string EndTime { get; set; }
        public int Break1 { get; set; }
        public int Break2 { get; set; }
        public string Break1BeginTime { get; set; }
        public string Break2BeginTime { get; set; }
        public string Break1EndTime { get; set; }
        public string Break2EndTime { get; set; }
        public int ShiftDuration { get; set; }
        public int Break1Duration { get; set; }
        public int Break2Duration { get; set; }
        public string ShiftType { get; set; }
        public int RecordStatus { get; set; }
        public int PunchBeginDuration { get; set; }
        public int PunchEndDuration { get; set; }
        public int IsGraceTimeApplicable { get; set; }
        public string GraceTime { get; set; }
        public int IsPartialDayApplicable { get; set; }
        public string PartialDay { get; set; }
        public string PartialDayBeginTime { get; set; }
        public string PartialDayEndTime { get; set; }
        public Nullable<int> IsPunchBeginDuration { get; set; }
        public Nullable<int> IsPunchEndDuration { get; set; }
        public Nullable<int> IsMarkHalfDayTime { get; set; }
        public string HalfDayDays { get; set; }
        public string MarkHalfDayTime { get; set; }
        public Nullable<int> IsFlexiShiftEndNextDay { get; set; }
        public string FlexiShiftNextDayEndTime { get; set; }
        public Nullable<int> IsPartialDay2Applicable { get; set; }
        public string PartialDay2 { get; set; }
        public string HalfDay2Days { get; set; }
        public string ShiftScheduleType { get; set; }
        public Nullable<int> FlexiShiftDuration { get; set; }
        public Nullable<int> FlexiShiftBreakDuration { get; set; }
        public string HalfDayStartFrom { get; set; }
        public Nullable<int> HalfDayGraceTime { get; set; }
    }
}
