//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser : HR2.EF.DAL.IEFEntity
    {
        public int UserId { get; set; }
        public string LoginName { get; set; }
        public string LoginPassword { get; set; }
        public string RoleName { get; set; }
        public int IsAdmin { get; set; }
        public Nullable<int> RecordStatus { get; set; }
        public Nullable<int> AccessI { get; set; }
        public string LastLogin { get; set; }
    }
}
