//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheetHour : HR2.EF.DAL.IEFEntity
    {
        public int TimeSheetHoursId { get; set; }
        public Nullable<int> EmployeesTimeSheetId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ProjectActivityId { get; set; }
        public Nullable<int> MondayHour { get; set; }
        public Nullable<int> TuesdayHour { get; set; }
        public Nullable<int> WednesdayHour { get; set; }
        public Nullable<int> ThursdayHour { get; set; }
        public Nullable<int> FridayHour { get; set; }
        public Nullable<int> SaturdayHour { get; set; }
        public Nullable<int> SundayHour { get; set; }
    }
}
