//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training : HR2.EF.DAL.IEFEntity
    {
        public int TrainingId { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> DateSchedule { get; set; }
        public Nullable<int> CoordinatorId { get; set; }
        public string Status { get; set; }
        public string TrainingTime { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
    }
}
