//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR2.Web.DataAccessLayer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataAccessLayer.IHR2DataAccessLayer")]
    public interface IHR2DataAccessLayer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR2DataAccessLayer/DoWork", ReplyAction="http://tempuri.org/IHR2DataAccessLayer/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR2DataAccessLayer/DoWork", ReplyAction="http://tempuri.org/IHR2DataAccessLayer/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHR2DataAccessLayerChannel : HR2.Web.DataAccessLayer.IHR2DataAccessLayer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HR2DataAccessLayerClient : System.ServiceModel.ClientBase<HR2.Web.DataAccessLayer.IHR2DataAccessLayer>, HR2.Web.DataAccessLayer.IHR2DataAccessLayer {
        
        public HR2DataAccessLayerClient() {
        }
        
        public HR2DataAccessLayerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HR2DataAccessLayerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HR2DataAccessLayerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HR2DataAccessLayerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
